### ISSUE TITLE
Add Mesh to make Cardano development accessible

### ISSUE THREAD

**Issue by jinglescode** [txpipe/wallet-connect-starter-kit#2]
Hi txpipe team, awesome work you got!

I want to reach out to introduce to [Mesh](https://mesh.martify.io/), as I think we have similar goals, to make Cardano development more accessible. What do you think about including Mesh in this package. It will help more developers to build on Cardano. 

In our next release, we are introducing useful hooks and UI components, you will love it, the developers gonna love it too. 

Lets speak.

**Comment by rvcas** [comment]
@jinglescode The more the merrier. Feel free to come to the discord if you want to speak more directly with the team. But yes, there's no reason not to have some examples with mesh.
